name: sic-test-windows

on:
  workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Cythonize
      run: |
        python test\compile.py build_ext --inplace
        mkdir bin
        move sic\*.pyd bin
        copy sic\__init__.py bin
        copy sic\*.xml bin
    - name: Unit tests
      run: |
        python test\ut_sic.py
    - name: Performance assessment
      run: |
        python test\performance.py
